# Generated by Django 3.1.5 on 2021-01-31 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Blog Tag', 'verbose_name_plural': 'Blog Tags'},
        ),
    ]
