# Generated by Django 3.1.5 on 2021-01-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0002_auto_20210131_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='visit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
