# Generated by Django 3.1.5 on 2021-02-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0005_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop_blog.blog'),
            preserve_default=False,
        ),
    ]
