# Generated by Django 3.1.5 on 2021-02-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0006_blogcomment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
