# Generated by Django 3.1.5 on 2021-02-01 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0007_blogcomment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
