# Generated by Django 3.1.5 on 2021-02-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0011_auto_20210201_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='visit',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
