# Generated by Django 3.1.5 on 2021-02-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0012_auto_20210201_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='visit',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
