# Generated by Django 3.1.5 on 2021-02-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_sliders', '0003_auto_20210202_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='sliders', verbose_name='image (1100 * 414)'),
        ),
    ]
