# Generated by Django 3.1.5 on 2021-02-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='site_logo',
            field=models.ImageField(default='', upload_to='site_setting/logo'),
        ),
    ]
