# Generated by Django 3.1.5 on 2021-01-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0, max_length=1000000)),
                ('size', models.CharField(choices=[('g1', 'XS '), ('g2', 'XS - S'), ('g3', 'XS - S - M'), ('g4', 'XS - S - M - L'), ('g5', 'XS - S - M - L - XL'), ('g6', 'XS - S - M - L - XL - XXL'), ('g7', 'XS - S - M - L - XL - XXL - 1X'), ('g8', 'XS - S - M - L - XL - XXL - 1X - 2X'), ('g9', 'XS - S - M - L - XL - XXL - 1X - 2X - 3X'), ('g10', 'XS - S - M - L - XL - XXL - 1X - 2X - 3X - 4X'), ('g11', 'XS - S - M - L - XL - XXL - 1X - 2X - 3X - 4X - 5X'), ('g12', 'XS - S - M - L - XL - XXL - 1X - 2X - 3X - 4X - 5X - 6X')], default=None, max_length=1000)),
                ('color', models.CharField(choices=[('r', 'red'), ('y', 'yellow'), ('g', 'green'), ('b', 'blue'), ('w', 'white'), ('bk', 'black'), ('o', 'orange'), ('p', 'pink'), ('be', 'beige '), ('gy', 'gray')], default=None, max_length=1000)),
                ('discount', models.IntegerField(choices=[('10', 10), ('20', 20), ('30', 30), ('40', 40), ('50', 50), ('60', 60), ('70', 70), ('80', 80), ('90', 90), ('100', 100)], default=0, max_length=100)),
                ('is_discount', models.BooleanField(default=False, verbose_name='It has a discount / no discount')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activate / deactivate')),
                ('reviews', models.IntegerField(default=0)),
                ('is_favorite', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
