# Generated by Django 3.1.5 on 2021-01-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0002_auto_20210130_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='product/images'),
            preserve_default=False,
        ),
    ]
