# Generated by Django 3.1.5 on 2021-01-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/images', verbose_name='image(800*800)'),
        ),
    ]
