# Generated by Django 3.1.5 on 2021-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0004_auto_20210130_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, choices=[('10', 10), ('20', 20), ('30', 30), ('40', 40), ('50', 50), ('60', 60), ('70', 70), ('80', 80), ('90', 90), ('100', 100)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_favorite',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
