# Generated by Django 3.1.5 on 2021-01-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0011_auto_20210130_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('g2', 'XS - S'), ('g3', 'XS - S - M'), ('g4', 'XS - S - M - L'), ('g5', 'XS - S - M - L - XL'), ('g6', 'XS - S - M - L - XL - XXL'), ('g7', 'XS - S - M - L - XL - XXL - 1X'), ('g8', 'XS - S - M - L - XL - XXL - 1X - 2X'), ('g9', 'XS - S - M - L - XL - XXL - 1X - 2X - 3X'), ('g10', 'XS - S - M - L - XL - XXL - 1X - 2X - 3X - 4X'), ('g11', 'XS - S - M - L - XL - XXL - 1X - 2X - 3X - 4X - 5X'), ('g12', 'XS - S - M - L - XL - XXL - 1X - 2X - 3X - 4X - 5X - 6X')], default=None, max_length=1000),
        ),
    ]
