# Generated by Django 3.1.5 on 2021-01-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0012_auto_20210130_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('XS - S', 'XS - S'), ('XS - S - M', 'XS - S - M'), ('XS - S - M - L', 'XS - S - M - L'), ('XS - S - M - L - XL', 'XS - S - M - L - XL'), ('XS - S - M - L - XL - XXL', 'XS - S - M - L - XL - XXL'), ('XS - S - M - L - XL - XXL - 1X', 'XS - S - M - L - XL - XXL - 1X'), ('XS - S - M - L - XL - XXL - 1X - 2X', 'XS - S - M - L - XL - XXL - 1X - 2X'), ('XS - S - M - L - XL - XXL - 1X - 2X - 3X', 'XS - S - M - L - XL - XXL - 1X - 2X - 3X'), ('XS - S - M - L - XL - XXL - 1X - 2X - 3X - 4X', 'XS - S - M - L - XL - XXL - 1X - 2X - 3X - 4X'), ('XS - S - M - L - XL - XXL - 1X - 2X - 3X - 4X - 5X', 'XS - S - M - L - XL - XXL - 1X - 2X - 3X - 4X - 5X'), ('XS - S - M - L - XL - XXL - 1X - 2X - 3X - 4X - 5X - 6X', 'XS - S - M - L - XL - XXL - 1X - 2X - 3X - 4X - 5X - 6X')], default=None, max_length=1000),
        ),
    ]
