# Generated by Django 3.1.5 on 2021-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_categories', '0001_initial'),
        ('shop_products', '0014_auto_20210130_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='shop_categories.Category'),
        ),
    ]
