# Generated by Django 3.1.5 on 2021-01-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0018_productcomment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='id_number',
            field=models.IntegerField(default=1),
        ),
    ]
