# Generated by Django 3.1.5 on 2021-01-31 09:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0019_productcomment_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='made_in',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
    ]
