# Generated by Django 3.1.5 on 2021-01-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0020_product_made_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='', max_length=500),
        ),
    ]
