# Generated by Django 3.1.5 on 2021-01-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_categories', '0001_initial'),
        ('shop_products', '0021_auto_20210131_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='shop_categories.Category'),
        ),
    ]
