# Generated by Django 3.1.5 on 2021-02-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0022_auto_20210131_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='visit_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
