# Generated by Django 3.1.5 on 2021-02-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0024_auto_20210201_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='comment_count',
        ),
        migrations.AddField(
            model_name='product',
            name='comment_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
