# Generated by Django 3.1.5 on 2021-02-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0025_auto_20210201_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment_count',
        ),
    ]
