# Generated by Django 3.1.5 on 2021-01-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='product_pk',
            field=models.IntegerField(default=0),
        ),
    ]
