# Generated by Django 3.1.5 on 2021-01-31 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0002_orderdetail_product_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_pk',
        ),
    ]
