# Generated by Django 3.1.5 on 2021-01-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0003_remove_orderdetail_product_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='price_discount',
            field=models.IntegerField(default=0),
        ),
    ]
