# Generated by Django 3.1.5 on 2021-01-31 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0004_orderdetail_price_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='price_discount',
        ),
    ]
