# Generated by Django 3.1.5 on 2021-02-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='galleries',
        ),
        migrations.AddField(
            model_name='aboutusgallery',
            name='about_us',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop_about_us.aboutus'),
            preserve_default=False,
        ),
    ]
