# Generated by Django 3.1.5 on 2021-02-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_about_us', '0003_auto_20210201_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='AboutUs/Gallery')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_about_us.aboutus')),
            ],
        ),
    ]
