# Generated by Django 3.1.5 on 2021-02-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_about_us', '0004_auto_20210201_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default='', upload_to='AboutUs/Gallery'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
